### PR TITLE
Fix parsing of getelementptr and load instructions

### PR DESCRIPTION
**Pull request by cocreature**
This fixes two of the issues in #23

### CODE REVIEW

**Comment by sdiehl** [comment]
I don't think this preserves the parser. Tests don't seem to pass on instruction-level quoter.

**Comment by cocreature** [comment]
Ah good catch, I forgot to run the test suite. I’ve updated the tests to the syntax that LLVM itself as well as this PR expects.

**Comment by nwtgck** [comment]
Thank you @cocreature.
Here is just my opinions as a library user.  I'd like to know your ideas.

---

## 1

This changes allows invalid LLVM IR like the following because the parser just ignore the first type.

```hs
loadInstr1 :: Operand -> Instruction
loadInstr1 op1 = [lli|load i64, i8* %myptr|]
```

## 2

So library users have to write the following. Every `load` and `gep` needs `typeOf`.

```hs
import LLVM.AST.Typed

loadInstr2 :: Operand -> Instruction
loadInstr2 op1 =
 let op1Type = typeOf op1
 in [lli|load $type:op1Type, $opr:op1|]
```

Before this PR, library users can write like the following

```hs
loadInstr2 :: Operand -> Instruction
loadInstr2 op1 =[lli|load $opr:op1|]
```

## 3

However, library users, who knows internal of llvm-hs-quote parser can write the following instead of `typeOf`.

```hs
-- Weird but works
loadInstr2' :: Operand -> Instruction
loadInstr2' op1 = [lli|load %DUMMY_TYPE, $opr:op1|]
```

I'd like to know what you think about these.

**Comment by cocreature** [comment]
> This changes allows invalid LLVM IR like the following because the parser just ignore the first type.

I’ve thought about this but wasn’t sure if the complexity of validating the type here is worth the trouble. Thinking about it again it probably is, so I’ll add it later.

As for 2 and 3. I don’t see why you would use `llvm-hs-quote` for this. If you just want to generate a single instruction, using the AST in `llvm-hs-pure` directly or the convenience wrappers in the `LLVM.IRBuilder` seems easier.

**Comment by nwtgck** [comment]
I love the concept of `LLVM.IRBuilder`. I created similar one and use it to use some additional features for my project. 

> As for 2 and 3. I don’t see why you would use llvm-hs-quote for this.

My usage of llvm-hs-quote like the following.

```hs
do
  valuePtr <- emitInstr [lli|alloca i32|]
  emitInstr [lli|store i32 8, $opr:valuePtr|]
  value    <- emitInstr [lli|load $opr:valuePtr|]
  ...
```

(Actual `emitInstr` needs `retty` as return-type. But in my implementation, `AST.Instruction` is a instance of `AST.Typed` partially. So it doesn't need `retty`.)

The reason why I use `[lli|alloca i32|]` instead of `alloca :: Type -> Maybe Operand -> Word32 -> m Operand` is that almost my `alloca` instructions don't need alignment. But `alloca :: Type -> ...` needs an alignment. In addition, when in the future I may want to put metadata to `[lli|alloca...|]`, it's easier to do that. The same things can be said in the other instructions. 

> using the AST in llvm-hs-pure directly

I don't write directory because it's so long and not readable. 

So I love llvm-hs-quote because it is very readable, very extensible and type-safe.

**Comment by sdiehl** [comment]
> I don't write directory because it's so long and not readable.

I think you should look into [IRBuilder](https://hackage.haskell.org/package/llvm-hs-pure-6.0.0/docs/LLVM-IRBuilder-Instruction.html), it's probably much more concise then you think. The quasiquoter is great if you have big blobs (module, functions, blocks, etc) of LLVM IR you need to directly splice into a module, but at the instruction-level I think it's a bit overkill and we already have an interface for interactively building it up like you would do in the backend to a compiler.

https://github.com/llvm-hs/llvm-hs/blob/llvm-6/llvm-hs-pure/test/LLVM/Test/IRBuilder.hs#L254
https://github.com/llvm-hs/llvm-hs-examples/blob/master/irbuilder/Main.hs#L19

**Comment by cocreature** [comment]
> The reason why I use [lli|alloca i32|] instead of alloca :: Type -> Maybe Operand -> Word32 -> m Operand is that almost my alloca instructions don't need alignment. But alloca :: Type -> ... needs an alignment. In addition, when in the future I may want to put metadata to [lli|alloca...|], it's easier to do that. The same things can be said in the other instructions.

Couldn’t you just define a wrapper around `alloca` that doesn’t require the alignment attribute? Maybe our development workflows are just different but personally, I find the ergonomics of quasi quoters to be significantly worse than those of regular Haskell code so unless there is a good reason to reach for one, I would just stick to regular Haskell code.

**Comment by nwtgck** [comment]
Thank you very much for your ideas, both @sdiehl  and @cocreature.

> I think you should look into IRBuilder, it's probably much more concise then you think. 

I'll learn about IRBuilder more. Thank you for your useful and helpful links of examples. 

>  I find the ergonomics of quasi quoters to be significantly worse than those of regular Haskell code so unless there is a good reason to reach for one, I would just stick to regular Haskell code.

Thank you very much to tell your experience. I'll think about quasi quoters again.

**Pull request merged**
